description: DeepSeek-Prover-V2 API

env_defaults:
  GPUS: 8
  PORT: 30004
  MODEL: deepseek-ai/DeepSeek-Prover-V2-671B

target:
  service: sing
  workspace_name: srgxws
  name: palisades33

environment:
  image: amlt-sing/acpt-torch2.7.1-py3.10-cuda12.6-ubuntu22.04
  setup:
    - sudo apt update
    - python -m pip install --upgrade pip
  
code:
  local_dir: $CONFIG_DIR/deepseek_prover_v2

jobs:
- name: deepseek-prover-v2-api-tianshixu-${PORT}
  sku: 4x40G8-A100
  # instance: ND96isr_MI300X_v5-n1
  priority: high
  sla_tier: premium       # Default: premium
  execution_mode: basic   # Default: basic
  identity: managed
  submit_args:
    env:
      NCCL_DEBUG: "ERROR"
      _AZUREML_SINGULARITY_JOB_UAI: /subscriptions/e546c811-2312-46e2-9fd0-c949c65da4d9/resourcegroups/srgx/providers/Microsoft.ManagedIdentity/userAssignedIdentities/srgxuai
  tags: [Project_Name:DeepSeek-Prover-V2, Quota:Extra, Debug:Yes]
  command:
  # 打招呼
  - hostname
  - nvidia-smi
  - sudo apt install screen
  - sudo apt install vim -y
  - sudo apt install sshpass -y
  - sudo apt install nginx -y

  # 最好标明具体的版本
  - pip install transformers==4.51.2
  - pip install vllm==0.7.3
  - pip install openai

  # 定时查询
  - screen -dmS times bash -c 'pip install openai; python times.py --port ${PORT} --model ${MODEL} --sleep 1; exec bash'
  # SSH连接
  - screen -dmS sshs bash -c 'bash ssh.sh ${PORT}; exec bash'
   
  # 启动程序
  - export MODEL_PATH=${MODEL}
  - export GPU_COUNT=${GPUS}
  - export PUBLIC_PORT=${PORT}
  - bash nginx/deploy_nginx.sh

  # 防止挂掉
  - nvidia-smi
  - sleep infinity