model_id: "checkpoints/sft_correct/sft_1024_correct"

train_dir: "data/math_hf/train.jsonl"
valid_dir: "data/math_hf/test.jsonl"
train_batch_size: 64
n_grpo_steps: 40
learning_rate: 1e-5
advantage_eps: 1e-6
rollout_batch_size: 256
group_size: 8
sampling_temperature: 1.0
sampling_min_tokens: 4
sampling_max_tokens: 1024
epochs_per_rollout_batch: 4
gradient_accumulation_steps: 64
gpu_memory_utilization: 0.3
seed: 3407

log_name: "rl_grpo_clip_offpolicy"
out_path: "checkpoints/rl_grpo_clip_offpolicy"
wandb_name: "cs336_assignment5_rl"