model_id: "checkpoints/sft_correct/sft_1024_correct"

train_dir: "data/math_hf/train.jsonl"
valid_dir: "data/math_hf/test.jsonl"
train_batch_size: 256
n_grpo_steps: 200
learning_rate: 1e-5
advantage_eps: 1e-6
rollout_batch_size: 256
group_size: 8
sampling_temperature: 1.0
sampling_min_tokens: 4
sampling_max_tokens: 1024
epochs_per_rollout_batch: 1
gradient_accumulation_steps: 256
gpu_memory_utilization: 0.25
seed: 3407

log_name: "rl_baseline"
out_path: "checkpoints/rl_baseline"
wandb_name: "cs336_assignment5_rl"